Update constants.py
Bugs fixed:
urllib.error.HTTPError: HTTP Error 400: Bad Request
instagram_private_api.errors.ClientCheckpointRequiredError: checkpoint_challenge_required

New values are set:
APP_VERSION
VERSION_CODE